notifications:
    email:
        on_success: never
        on_failure: always
language: python
python: 3.6
addons:
    apt:
        update: true
env:
    global:
        - GH_USER=Twiddly
        - GH_MAIL=pew@pewpew.moe
        - REPO=happypandax/plugins
        - secure: sogo+NT/2/Xr1LNmksFbMSoGCNCgVUcQynhkBiLqSfLrfT9zDXVYl4FGqIntARJSNK1BTvayV/XD0HOtMzbjeARoR91+NYgPScV3PRDu/Bw+X4yM8jjN7GZjz5+a5+co+A8cfuKdrf93CNVV6N02fxzqdC9lhoyp+HD7JxbWKl2+8YmQetrAD4dGf+KaVcJKHr/pgpBND5Tp17jO4vAEbqD+GT7aXDoC+81Onq8UOzNI0/A9s+2IzMlG4Jhfdr52ynpND1plycspByVI3kRqrFPEcWk4x2U5C8OKU6Hf4Zuj3G1d37c8MP6F9F362m6MWa4cfxOeKCmP6uRSVEf9Oxb/w2OnEg40U5nYEpBvziml1STINSgQQlwI4+iO0o1G4Zl7nRsyICZEAhzJRjoPcF5+IfzjGera0xxFkVd+0A9fz8kAyTp53BK5uAxgiaLcIfVj9WsZhSuJPG4kx0abnaNLPJtrDDTdBX9+A0Xk9sXHBCphFVOhobTUspmpCN4zWO9jH8xcPotRyo4D53I7yapSiia89yDxQNLnoNGDVPuX4KTMWO9w2snczEKo9rSJUDJVqdRU1LXbERFCoyCd33Rfm9EZsR06mtkjkpAL7YWOfbjSlyes87OBS3sRW7FqmQPEgSVbovmygOa564Yfo9B48doSKtg09aj0IBJxxXk=


script:
    - python3 build.py
    - git config --local user.name "$GH_USER"
    - git config --local user.email "$GH_MAIL"
    - git commit -am "build"
    - git push --quiet "https://$GITHUB_TOKEN@github.com/$REPO.git" master > /dev/null 2>&1
